#!/usr/bin/env python3
"""Build the preregistered, distinct V4.12 synthetic S0-R2 fixture.

This adapter verifies the consumed R1 receipt and the immutable core fixture
producer before reusing that producer's payload construction helpers.  It
never reads CRM data: the CSV comes from the pinned core plan and the empty
Parquet is generated by the pinned core builder.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import re
import stat
from pathlib import Path
from types import ModuleType
from typing import Any, Mapping


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
AUTHORITATIVE_PLAN_PATH = (
    REPOSITORY_ROOT / "config/v4_12_fresh_s0_authoritative_run_plan.json"
)
R2_ROOT = Path(
    "/Volumes/CATNAT_DATA/SIRETO_RECALL100/"
    "fresh_holdout_intake_synthetic_r2"
)
EXPECTED_R2_RUN_ID = (
    "bjpoibmapghmeklagcnddeamijgmlfijmifdobbmmanmohkknplbpolonjfjahlo"
)
RUN_DOMAIN = "SIRETO-V412-FRESH-SYNTHETIC-S0-R2-RUN-ID\0"
RUN_PROJECTION = (
    "fixture_spec_sha256",
    "core_plan_sha256",
    "predecessor_receipt_sha256",
)
ATTEMPT_DOMAIN = "SIRETO-V412-FRESH-SYNTHETIC-ATTEMPT-ID\0"
ATTEMPT_PROJECTION = (
    "synthetic_run_id",
    "fixture_control_manifest_sha256",
    "logical_time_utc",
)
DERIVATION_ALGORITHM = (
    "SHA256_DOMAIN_UTF8_CONCAT_CANONICAL_JSON_SORT_KEYS_COMPACT_UTF8_NO_LF_"
    "THEN_MAP_HEX_NIBBLES_0_TO_F_TO_ASCII_A_TO_P"
)
EXPECTED_ATTEMPT_VALUES = {
    "synthetic_run_id": "EQUAL_R2_RUN_DERIVATION_RESULT",
    "fixture_control_manifest_sha256": (
        "SHA256_EXACT_NEW_R2_CANONICAL_CONTROL_MANIFEST_BYTES"
    ),
    "logical_time_utc": "LITERAL_EQUAL_CORE_FIXTURE_LOGICAL_TIME_UTC",
}
CORE_PIN_ROLES = ("contract", "fixture_builder", "plan", "scanner", "tests")
PIN_FIELDS = {"path", "sha256"}
HEX64 = re.compile(r"^[0-9a-f]{64}$")
EMPTY_SHA256 = hashlib.sha256(b"").hexdigest()


class R2FixtureBuildError(RuntimeError):
    """Fail-closed R2 fixture construction error."""


def _stop(message: str) -> None:
    raise R2FixtureBuildError(message)


def canonical_json_bytes(value: Any, *, final_lf: bool = True) -> bytes:
    raw = json.dumps(
        value,
        ensure_ascii=False,
        allow_nan=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return raw + (b"\n" if final_lf else b"")


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def opaque_digest(domain: str, payload: Mapping[str, Any]) -> str:
    digest = hashlib.sha256(
        domain.encode("utf-8") + canonical_json_bytes(payload, final_lf=False)
    ).hexdigest()
    return "".join(chr(ord("a") + int(nibble, 16)) for nibble in digest)


def _normalized_absolute(path: Path, label: str) -> Path:
    raw = os.fspath(path)
    if not path.is_absolute() or "\x00" in raw:
        _stop(f"{label} must be an absolute path")
    normalized = Path(os.path.abspath(raw))
    if path != normalized or any(part in {"", ".", ".."} for part in path.parts):
        _stop(f"{label} must be normalized")
    return normalized


def _read_regular_anchored(
    path: Path,
    label: str,
    *,
    expected_uid: int | None = None,
) -> tuple[bytes, os.stat_result]:
    normalized = _normalized_absolute(Path(path), label)
    directory_flags = (
        os.O_RDONLY
        | getattr(os, "O_DIRECTORY", 0)
        | getattr(os, "O_NOFOLLOW", 0)
        | getattr(os, "O_CLOEXEC", 0)
    )
    file_flags = (
        os.O_RDONLY
        | getattr(os, "O_NOFOLLOW", 0)
        | getattr(os, "O_CLOEXEC", 0)
    )
    descriptor = os.open("/", directory_flags)
    try:
        for component in normalized.parts[1:-1]:
            child = os.open(
                component, directory_flags, dir_fd=descriptor
            )
            os.close(descriptor)
            descriptor = child
        file_descriptor = os.open(
            normalized.name, file_flags, dir_fd=descriptor
        )
    except OSError as exc:
        _stop(f"{label} cannot be opened safely: {exc}")
    finally:
        os.close(descriptor)

    try:
        before = os.fstat(file_descriptor)
        uid = os.getuid() if expected_uid is None else expected_uid
        if (
            not stat.S_ISREG(before.st_mode)
            or before.st_uid != uid
            or before.st_nlink != 1
            or stat.S_IMODE(before.st_mode) & 0o022
        ):
            _stop(f"{label} identity or permissions are unsafe")
        chunks: list[bytes] = []
        while True:
            chunk = os.read(file_descriptor, 65536)
            if not chunk:
                break
            chunks.append(chunk)
        after = os.fstat(file_descriptor)
        identity_fields = (
            "st_dev",
            "st_ino",
            "st_size",
            "st_mtime_ns",
            "st_ctime_ns",
            "st_uid",
            "st_nlink",
            "st_mode",
        )
        if any(
            getattr(before, field) != getattr(after, field)
            for field in identity_fields
        ):
            _stop(f"{label} changed while being read")
        raw = b"".join(chunks)
        if len(raw) != before.st_size:
            _stop(f"{label} size changed while being read")
        return raw, before
    finally:
        os.close(file_descriptor)


def _read_canonical_json(path: Path, label: str) -> tuple[dict[str, Any], bytes]:
    try:
        raw, _ = _read_regular_anchored(path, label)
        value = json.loads(raw)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        _stop(f"{label} is unreadable or invalid: {exc}")
    if not isinstance(value, dict) or raw != canonical_json_bytes(value):
        _stop(f"{label} is not a canonical JSON object with one final LF")
    return value, raw


def _repo_path(value: str) -> Path:
    path = Path(value)
    if (
        path.is_absolute()
        or not path.parts
        or any(part in {"", ".", ".."} for part in path.parts)
    ):
        _stop("repository authority path is invalid")
    candidate = REPOSITORY_ROOT.joinpath(path)
    try:
        candidate.relative_to(REPOSITORY_ROOT)
    except ValueError:
        _stop("repository authority escapes the repository")
    return candidate


def _validate_pin_record(value: Any, label: str) -> tuple[Path, str]:
    if (
        not isinstance(value, dict)
        or set(value) != PIN_FIELDS
        or not isinstance(value["path"], str)
        or not isinstance(value["sha256"], str)
        or not HEX64.fullmatch(value["sha256"])
    ):
        _stop(f"{label} pin record is invalid")
    return _repo_path(value["path"]), value["sha256"]


def _validate_derivations(
    successor: Mapping[str, Any],
    core_plan: Mapping[str, Any],
) -> None:
    run = successor.get("run_derivation")
    attempt = successor.get("attempt_derivation")
    if not isinstance(run, dict) or not isinstance(attempt, dict):
        _stop("R2 derivation authorities are missing")
    if (
        run.get("algorithm") != DERIVATION_ALGORITHM
        or run.get("domain") != RUN_DOMAIN
        or tuple(run.get("projection", ())) != RUN_PROJECTION
        or not isinstance(run.get("values"), dict)
        or set(run["values"]) != set(RUN_PROJECTION)
    ):
        _stop("R2 run derivation authority mismatch")
    if (
        attempt.get("algorithm") != DERIVATION_ALGORITHM
        or attempt.get("domain") != ATTEMPT_DOMAIN
        or tuple(attempt.get("projection", ())) != ATTEMPT_PROJECTION
        or attempt.get("values") != EXPECTED_ATTEMPT_VALUES
    ):
        _stop("R2 attempt derivation authority mismatch")
    core_attempt = core_plan.get("ids", {}).get("attempt")
    if (
        not isinstance(core_attempt, dict)
        or core_attempt.get("domain") != ATTEMPT_DOMAIN
        or tuple(core_attempt.get("projection", ())) != ATTEMPT_PROJECTION
    ):
        _stop("R2 attempt derivation differs from immutable core")


def _load_authorities(
    authoritative_plan_path: Path,
) -> tuple[dict[str, Any], dict[str, Any], ModuleType, bytes]:
    plan_path = _normalized_absolute(
        Path(authoritative_plan_path), "authoritative R2 plan path"
    )
    plan, _ = _read_canonical_json(
        plan_path, "authoritative R2 plan"
    )
    contract_path, contract_sha256 = _validate_pin_record(
        plan.get("contract"), "authoritative contract"
    )
    contract_bytes, _ = _read_regular_anchored(
        contract_path, "authoritative contract"
    )
    if sha256_bytes(contract_bytes) != contract_sha256:
        _stop("authoritative contract pin mismatch")

    successor = plan.get("r2_successor")
    if not isinstance(successor, dict):
        _stop("authoritative plan has no R2 successor authority")
    if successor.get("builder_path") != (
        "scripts/build_v412_fresh_s0_r2_fixture.py"
    ):
        _stop("R2 builder path authority mismatch")
    planned_root = _normalized_absolute(
        Path(successor.get("root", "")), "R2 planned root"
    )
    if plan_path == AUTHORITATIVE_PLAN_PATH and planned_root != R2_ROOT:
        _stop("production R2 root differs from the preregistered constant")

    core = plan.get("core")
    if not isinstance(core, dict) or core.get("immutable") is not True:
        _stop("core authority is not immutable")
    pins = core.get("pins")
    if not isinstance(pins, dict) or tuple(sorted(pins)) != tuple(
        sorted(CORE_PIN_ROLES)
    ):
        _stop("core pin role set mismatch")
    pinned_payloads: dict[str, bytes] = {}
    pinned_paths: dict[str, Path] = {}
    for role in CORE_PIN_ROLES:
        pinned_path, expected_sha256 = _validate_pin_record(
            pins[role], f"core {role}"
        )
        payload, _ = _read_regular_anchored(
            pinned_path, f"core {role}"
        )
        if sha256_bytes(payload) != expected_sha256:
            _stop(f"pinned core {role.replace('_', ' ')} hash mismatch")
        pinned_paths[role] = pinned_path
        pinned_payloads[role] = payload
    core_plan_path = pinned_paths["plan"]
    core_builder_path = pinned_paths["fixture_builder"]
    core_plan_bytes = pinned_payloads["plan"]
    core_builder_bytes = pinned_payloads["fixture_builder"]

    run_values = successor["run_derivation"]["values"]
    if run_values["core_plan_sha256"] != sha256_bytes(core_plan_bytes):
        _stop("R2 derivation does not pin the exact core plan bytes")

    try:
        core_plan = json.loads(core_plan_bytes)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        _stop(f"pinned core plan is invalid: {exc}")
    if core_plan_bytes != canonical_json_bytes(core_plan):
        _stop("pinned core plan is not canonical JSON")
    core_contract_record = pins["contract"]
    if core_plan.get("contract") != core_contract_record:
        _stop("pinned core plan does not name the pinned core contract")
    _validate_derivations(successor, core_plan)
    fixture_spec_sha256 = sha256_bytes(
        canonical_json_bytes(core_plan["fixture"], final_lf=False)
    )
    if (
        fixture_spec_sha256
        != core_plan["control_manifest"]["fixture_spec_sha256"]
        or fixture_spec_sha256 != run_values["fixture_spec_sha256"]
    ):
        _stop("R2 fixture spec does not equal the pinned core fixture")

    module_spec = importlib.util.spec_from_file_location(
        "_sireto_v412_pinned_core_fixture_builder", core_builder_path
    )
    if module_spec is None or module_spec.loader is None:
        _stop("cannot load pinned core fixture builder")
    core_builder = importlib.util.module_from_spec(module_spec)
    module_spec.loader.exec_module(core_builder)
    return plan, core_plan, core_builder, core_plan_bytes


def _read_and_verify_predecessor(
    successor: Mapping[str, Any],
    plan: Mapping[str, Any],
) -> bytes:
    receipt_path = _normalized_absolute(
        Path(successor["predecessor_receipt_absolute_path"]),
        "pinned R1 receipt path",
    )
    receipt_bytes, _ = _read_regular_anchored(
        receipt_path, "pinned R1 receipt"
    )
    receipt_sha256 = sha256_bytes(receipt_bytes)
    if receipt_sha256 != successor["predecessor_receipt_sha256"]:
        _stop("pinned R1 receipt hash mismatch")
    if (
        successor["run_derivation"]["values"][
            "predecessor_receipt_sha256"
        ]
        != receipt_sha256
    ):
        _stop("R2 run derivation does not bind the pinned R1 receipt")
    try:
        receipt = json.loads(receipt_bytes)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        _stop(f"pinned R1 receipt is invalid: {exc}")
    if receipt_bytes != canonical_json_bytes(receipt):
        _stop("pinned R1 receipt is not canonical JSON")

    receipt_contract = plan.get("launch_receipt")
    receipt_fields = (
        receipt_contract.get("exact_fields")
        if isinstance(receipt_contract, dict)
        else None
    )
    if (
        not isinstance(receipt, dict)
        or not isinstance(receipt_fields, list)
        or set(receipt) != set(receipt_fields)
        or receipt.get("schema_version")
        != receipt_contract.get("schema_version")
    ):
        _stop("pinned R1 receipt schema mismatch")

    worker = receipt.get("worker_receipt")
    worker_schema = plan.get("schema_definitions", {}).get(
        "worker_receipt_record", {}
    )
    expected = {
        "synthetic_run_id": successor["predecessor_run_id"],
        "attempt_id": successor["predecessor_attempt_id"],
        "phase": "WORKER",
        "reason_code": "WORKER_CONTROL_INVALID",
        "verdict": "STOP",
        "terminal_result": "STOP_SYNTHETIC_SCANNER_SEALER_V412",
    }
    if any(receipt.get(key) != value for key, value in expected.items()):
        _stop("pinned R1 receipt terminal authority mismatch")
    if (
        not isinstance(worker, dict)
        or set(worker) != set(worker_schema.get("exact_fields", ()))
        or not isinstance(worker.get("pid"), int)
        or isinstance(worker.get("pid"), bool)
        or worker["pid"] <= 0
        or worker.get("exit_code") != 65
        or worker.get("signal") is not None
        or worker.get("control_result") is not None
        or worker.get("stdout_size_bytes") != 0
        or worker.get("stdout_sha256") != EMPTY_SHA256
        or worker.get("stderr_size_bytes") != successor["r1_stderr_size_bytes"]
        or worker.get("stderr_sha256") != successor["r1_stderr_sha256"]
    ):
        _stop("pinned R1 worker failure authority mismatch")
    return receipt_bytes


def _control_object(
    core_plan: Mapping[str, Any],
    run_id: str,
    payloads: Mapping[str, bytes],
) -> dict[str, Any]:
    fixture = core_plan["fixture"]
    return {
        "schema_version": core_plan["control_manifest"]["schema"],
        "synthetic_fixture": True,
        "fixture_spec_sha256": core_plan["control_manifest"][
            "fixture_spec_sha256"
        ],
        "synthetic_run_id": run_id,
        "logical_time_utc": fixture["logical_time_utc"],
        "batch_count": 1,
        "expected_source_row_count": fixture["expected"]["source_row_count"],
        "producer_exclusions": [],
        "collection_source_manifest_sha256": sha256_bytes(
            payloads["collection_source_manifest.json"]
        ),
        "source_manifest_sha256": sha256_bytes(
            payloads["source_manifest.json"]
        ),
        "crm_safe_csv_sha256": sha256_bytes(payloads["crm_safe.csv"]),
        "evidence_source_manifest_sha256": sha256_bytes(
            payloads["evidence_source_manifest.json"]
        ),
        "evidence_source_parquet_sha256": sha256_bytes(
            payloads["evidence_source.parquet"]
        ),
    }


def _assert_only_preregistered_differences(
    core_builder: ModuleType,
    core_plan: Mapping[str, Any],
    predecessor_run_id: str,
    r2_run_id: str,
    r2_payloads: Mapping[str, bytes],
    r2_control: Mapping[str, Any],
) -> None:
    csv_bytes = core_plan["fixture"]["csv"]["exact_utf8_text"].encode("utf-8")
    evidence_bytes = r2_payloads["evidence_source.parquet"]
    r1_payloads = core_builder._manifest_objects(
        core_plan, predecessor_run_id, csv_bytes, evidence_bytes
    )
    for name in ("crm_safe.csv", "evidence_source.parquet"):
        if r1_payloads[name] != r2_payloads[name]:
            _stop(f"R2 immutable payload changed: {name}")

    for name in (
        "collection_source_manifest.json",
        "source_manifest.json",
        "evidence_source_manifest.json",
    ):
        try:
            r1_manifest = json.loads(r1_payloads[name])
            r2_manifest = json.loads(r2_payloads[name])
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            _stop(f"generated manifest is invalid: {exc}")
        if (
            r1_payloads[name] != canonical_json_bytes(r1_manifest)
            or r2_payloads[name] != canonical_json_bytes(r2_manifest)
        ):
            _stop(f"generated manifest is not canonical: {name}")
        if set(r1_manifest) != set(r2_manifest):
            _stop(f"R2 manifest keys changed: {name}")
        changed = {
            key
            for key in r1_manifest
            if r1_manifest[key] != r2_manifest[key]
        }
        if changed != {"synthetic_run_id"}:
            _stop(f"R2 manifest has non-allowlisted changes: {name}")
        if (
            r1_manifest["synthetic_run_id"] != predecessor_run_id
            or r2_manifest["synthetic_run_id"] != r2_run_id
        ):
            _stop(f"R2 manifest run id mismatch: {name}")

    r1_control = _control_object(core_plan, predecessor_run_id, r1_payloads)
    allowed_control_changes = {
        "synthetic_run_id",
        "collection_source_manifest_sha256",
        "source_manifest_sha256",
        "evidence_source_manifest_sha256",
    }
    if set(r1_control) != set(r2_control):
        _stop("R2 control manifest keys changed")
    changed = {
        key for key in r1_control if r1_control[key] != r2_control[key]
    }
    if changed != allowed_control_changes:
        _stop("R2 control manifest has non-transitive changes")


def _validate_build_root(
    root: Path,
    plan: Mapping[str, Any],
    core_builder: ModuleType,
) -> Path:
    requested = _normalized_absolute(Path(root), "requested R2 root")
    planned = _normalized_absolute(
        Path(plan["r2_successor"]["root"]), "planned R2 root"
    )
    if requested != planned:
        _stop("requested R2 root differs from the authoritative plan")
    validated = core_builder._validate_root(requested)
    if validated != requested:
        _stop("core root validation changed the authoritative R2 root")
    return requested


def build_fixture(
    *,
    root: Path,
    authoritative_plan_path: Path = AUTHORITATIVE_PLAN_PATH,
) -> dict[str, Any]:
    """Build one immutable R2 package from pinned, synthetic-only authorities."""

    old_umask = os.umask(0o077)
    try:
        plan, core_plan, core_builder, core_plan_bytes = _load_authorities(
            Path(authoritative_plan_path)
        )
        successor = plan["r2_successor"]
        root = _validate_build_root(root, plan, core_builder)
        receipt_bytes = _read_and_verify_predecessor(successor, plan)

        run_values = {
            "fixture_spec_sha256": core_plan["control_manifest"][
                "fixture_spec_sha256"
            ],
            "core_plan_sha256": sha256_bytes(core_plan_bytes),
            "predecessor_receipt_sha256": sha256_bytes(receipt_bytes),
        }
        run_id = opaque_digest(
            RUN_DOMAIN, run_values
        )
        if run_values != successor["run_derivation"]["values"]:
            _stop("R2 run derivation values differ from preregistration")
        if (
            run_id != EXPECTED_R2_RUN_ID
            or run_id == successor["predecessor_run_id"]
        ):
            _stop("R2 run id is not the distinct preregistered value")

        csv_bytes = core_plan["fixture"]["csv"]["exact_utf8_text"].encode(
            "utf-8"
        )
        evidence_bytes = core_builder._empty_evidence_parquet(core_plan)
        payloads = core_builder._manifest_objects(
            core_plan, run_id, csv_bytes, evidence_bytes
        )
        if set(payloads) != set(core_plan["input_package"]["exact_files"]):
            _stop("pinned core builder emitted an unexpected payload set")
        control = _control_object(core_plan, run_id, payloads)
        _assert_only_preregistered_differences(
            core_builder,
            core_plan,
            successor["predecessor_run_id"],
            run_id,
            payloads,
            control,
        )
        control_bytes = canonical_json_bytes(control)
        control_sha256 = sha256_bytes(control_bytes)
        attempt_values = {
            "synthetic_run_id": run_id,
            "fixture_control_manifest_sha256": control_sha256,
            "logical_time_utc": core_plan["fixture"]["logical_time_utc"],
        }
        if tuple(attempt_values) != ATTEMPT_PROJECTION:
            _stop("internal R2 attempt projection order mismatch")
        attempt_id = opaque_digest(ATTEMPT_DOMAIN, attempt_values)
        if attempt_id == successor["predecessor_attempt_id"]:
            _stop("R2 attempt id unexpectedly equals consumed R1 attempt")

        package = root / "inbox" / run_id / "package"
        control_dir = root / "control" / run_id
        core_builder._prepare_empty_root(root)
        for path in (
            root / "inbox",
            root / "inbox" / run_id,
            package,
            root / "control",
            control_dir,
        ):
            core_builder._mkdir_private(path)
        for name in core_plan["input_package"]["exact_files"]:
            core_builder._write_exclusive(package / name, payloads[name])

        control_path = control_dir / "fixture_control_manifest.json"
        core_builder._write_exclusive(control_path, control_bytes)

        for path in (
            package,
            package.parent,
            control_dir,
            control_dir.parent,
            root,
        ):
            fd = os.open(path, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
            try:
                os.fsync(fd)
            finally:
                os.close(fd)
        return {
            "synthetic_run_id": run_id,
            "attempt_id": attempt_id,
            "package_path": str(package),
            "control_manifest_path": str(control_path),
            "fixture_control_manifest_sha256": control_sha256,
            "core_plan_sha256": sha256_bytes(core_plan_bytes),
            "predecessor_receipt_sha256": sha256_bytes(receipt_bytes),
        }
    finally:
        os.umask(old_umask)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=R2_ROOT)
    args = parser.parse_args()
    if args.root != R2_ROOT:
        _stop("authoritative R2 build requires the exact preregistered root")
    result = build_fixture(root=args.root)
    print(canonical_json_bytes(result).decode("utf-8"), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
